version: '3'

services:
  mariadb:
    image: mariadb:10.6.14
    container_name: mi-maria-db
    restart: always
    ports:
      - 3306:3306
    environment:
      - MYSQL_ROOT_PASSWORD=secret
      - MYSQL_DATABASE=Mi-Maria-db

  mongodb:
    image: mongo:6.0
    container_name: mi-mongodb
    restart: always
    ports:
      - 27017:27017
    environment:
      - MONGO_INITDB_ROOT_USERNAME=AguasFsa
      - MONGO_INITDB_ROOT_PASSWORD=secretpassword
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: mi-app
    restart: always
    ports:
      - 3000:3000
    depends_on:
      - mariadb
      - mongodb

